languageCode = "en-us"
author       = "John Koelndorfer"
title        = "John Koelndorfer"
theme        = "hugo-goa"

relativeURLs = false
uglyURLs     = true

[params]
author      = "John Koelndorfer"
intro       = "Technologist and purveyor of fine automation"
description = "Senior Software Developer @ [AerisWeather](https://www.aerisweather.com)"
dateformat  = "2006-01-02"
authorimage = "personalphoto.jpg"

[params.social]
github   = "jkoelndorfer"
linkedin = "jkoelndorfer"
email    = "jkoelndorfer@gmail.com"

[[menu.main]]
name       = "about"
weight     = 100
identifier = "about"
url        = "/about/index.html"

[[menu.main]]
name       = "blog"
weight     = "200"
identifier = "blog"
url        = "/blog.html"
